import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.tsx',
    ],

    theme: {
        extend: {
            colors: {
                'surface-container-highest': '#e4e2e4',
                primary: '#000000',
                'outline-variant': '#c6c6cd',
                'tertiary-fixed-dim': '#b7c8e1',
                'on-tertiary-container': '#75859d',
                tertiary: '#000000',
                'on-error-container': '#93000a',
                'error-container': '#ffdad6',
                'on-tertiary-fixed-variant': '#38485d',
                'on-tertiary-fixed': '#0b1c30',
                'surface-tint': '#565e74',
                'on-primary': '#ffffff',
                'on-secondary-container': '#fefcff',
                'surface-container-low': '#f6f3f5',
                surface: '#fcf8fa',
                'on-surface': '#1b1b1d',
                'tertiary-container': '#0b1c30',
                'surface-bright': '#fcf8fa',
                'surface-container-high': '#eae7e9',
                'on-secondary': '#ffffff',
                'on-primary-fixed-variant': '#3f465c',
                'secondary-fixed': '#dbe1ff',
                'on-secondary-fixed-variant': '#003ea8',
                background: '#fcf8fa',
                'primary-fixed': '#dae2fd',
                'primary-container': '#131b2e',
                'on-primary-fixed': '#131b2e',
                'inverse-on-surface': '#f3f0f2',
                'surface-container-lowest': '#ffffff',
                'on-tertiary': '#ffffff',
                'on-surface-variant': '#45464d',
                'secondary-fixed-dim': '#b4c5ff',
                'inverse-surface': '#303032',
                'surface-container': '#f0edef',
                'primary-fixed-dim': '#bec6e0',
                outline: '#76777d',
                'secondary-container': '#316bf3',
                'on-error': '#ffffff',
                'surface-dim': '#dcd9db',
                'on-primary-container': '#7c839b',
                'inverse-primary': '#bec6e0',
                'surface-variant': '#e4e2e4',
                error: '#ba1a1a',
                'tertiary-fixed': '#d3e4fe',
                secondary: '#0051d5',
                'on-secondary-fixed': '#00174b',
                'on-background': '#1b1b1d',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                md: '16px',
                base: '4px',
                sm: '8px',
                xs: '4px',
                xl: '32px',
                'container-padding': '24px',
                lg: '24px',
                gutter: '16px',
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                'headline-md': ['Inter'],
                'body-md': ['Inter'],
                'display-lg': ['Inter'],
                'mono-md': ['JetBrains Mono'],
                'body-lg': ['Inter'],
                'headline-lg': ['Inter'],
                'body-sm': ['Inter'],
                'label-md': ['Inter'],
            },
            fontSize: {
                'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'mono-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
            },
        },
    },

    plugins: [forms],
};
